services:
  base-db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: pg1234
      PGDATA: /data/postgres
    networks:
      - base-network
    volumes:
      - base-db-volume:/var/lib/postgresql/data
    ports:
      - "5454:5432"
    hostname: database

networks:
  base-network:
    driver: bridge

volumes:
  base-db-volume:
